name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Lint (black)
        uses: psf/black@stable
        with:
          options: --check --diff
          src: .
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Lint (flake8)
        run: |
          flake8
      - name: Lint (isort)
        run: |
          isort --check .
      - name: Run tests
        run: |
          pytest -vv example/tests/
